/**
 * Compat shim: trustGate / trustLog / trustMeter
 *
 * Byte-for-byte behavioural match for the hand-copied `lib/platform-trust.ts`
 * template that currently lives in ~20 portfolio consumers (MMCBuild,
 * F2K-Checkpoint, Kira, Connexions, DealFindrs, etc.) generated by
 * platform-trust/scripts/portfolio-trust-middleware.ts.
 *
 * Ships alongside the newer primitive API (checkRateLimit, checkPermission,
 * logAuditEvent, meterCall) so existing call sites can keep working while
 * consumers migrate off the hand-copy pattern.
 *
 * IMPORTANT — behavioural difference vs the primitives:
 * - This shim's permission check is ALLOW-BY-DEFAULT (returns allowed=true
 *   when no policy is found for the agent/scope/operation tuple). That
 *   matches the hand-copied template verbatim.
 * - checkPermission primitive (checkPermission.ts) is DENY-BY-DEFAULT.
 * - Migration path for consumers that want tighter security: switch from
 *   this shim to the primitive API after confirming every production
 *   agent/scope/operation has an explicit policy row.
 *
 * BYOK CONFIG (added in 0.4.1):
 * - Each function accepts an optional `PlatformTrustConfig` (with
 *   `supabaseUrl` / `serviceKey` / `projectId`) so consumers can point at
 *   THEIR Supabase project rather than relying on the portfolio's shared
 *   PLATFORM_TRUST_* env vars. Explicit config beats env-var fallback.
 *
 * UNCONFIGURED-ENVIRONMENT BEHAVIOUR (changed in 0.4.0):
 * - Read operations: allowed (warning logged). Backward-compatible.
 * - Write/delete operations: DENIED. Returns allowed=false with a
 *   denial_reason that names the missing config. This closes the
 *   anti-pattern flagged in storefront-mcp/agent-attack.md (FINDING-02
 *   step 5, FINDING-04 step 2, FINDING-05 step 5) and Connexions/CLAUDE.md.
 * - Local-dev escape hatch: set PLATFORM_TRUST_DEV_OVERRIDE to the literal
 *   string "allow-unconfigured-writes" to restore the pre-0.4.0 fail-open
 *   behaviour. Loud warning is logged on every gate call when the override
 *   is active. Production environments must NEVER set this var.
 */

import { type SupabaseClient } from '@supabase/supabase-js'
import { createHash } from 'crypto'
import { getTrustClient, type PlatformTrustConfig } from './config'

// ── Public types (match the template exactly) ────────────────────
export interface TrustContext {
  agent_id: string
  session_id?: string
  tool_name: string
  operation_type: 'read' | 'write' | 'delete'
  scope: string
  input?: unknown
}

export interface TrustGateResult {
  allowed: boolean
  requires_approval: boolean
  denial_reason?: string
  audit_id?: string
  retry_after?: number
}

// ── Hash helper (Node crypto — same output format as template) ───
function hashData(data: unknown): string | null {
  if (data === undefined || data === null) return null
  const json = typeof data === 'string' ? data : JSON.stringify(data)
  return `sha256:${createHash('sha256').update(json).digest('hex')}`
}

// ── Rate Limiting (mirrors template logic) ───────────────────────
const WINDOW_SECONDS: Record<string, number> = { minute: 60, hour: 3600, day: 86400 }

async function shimCheckRateLimit(
  client: SupabaseClient,
  projectId: string,
  agent_id: string,
): Promise<{ allowed: boolean; retry_after?: number }> {
  const { data: limits } = await client
    .from('rate_limits')
    .select('*')
    .eq('project_id', projectId)
    .in('agent_id', [agent_id, '*'])
    .order('window_type')

  if (!limits || limits.length === 0) return { allowed: true }

  const now = new Date()
  for (const limit of limits) {
    const windowSeconds = WINDOW_SECONDS[limit.window_type]
    const windowStart = new Date(limit.window_start)
    const windowEnd = new Date(windowStart.getTime() + windowSeconds * 1000)

    if (now >= windowEnd) {
      await client
        .from('rate_limits')
        .update({
          current_count: 1,
          window_start: now.toISOString(),
          updated_at: now.toISOString(),
        })
        .eq('id', limit.id)
      continue
    }

    if (limit.current_count >= limit.max_requests) {
      return {
        allowed: false,
        retry_after: Math.ceil((windowEnd.getTime() - now.getTime()) / 1000),
      }
    }

    await client
      .from('rate_limits')
      .update({
        current_count: limit.current_count + 1,
        updated_at: now.toISOString(),
      })
      .eq('id', limit.id)
      .eq('current_count', limit.current_count)
  }

  return { allowed: true }
}

// ── Permission Check — ALLOW-BY-DEFAULT to match template ────────
async function shimCheckPermission(
  client: SupabaseClient,
  projectId: string,
  agent_id: string,
  scope: string,
  operation: string,
): Promise<{ allowed: boolean; requires_approval: boolean }> {
  const { data: policy } = await client
    .from('permission_policies')
    .select('*')
    .eq('project_id', projectId)
    .eq('agent_id', agent_id)
    .eq('scope', scope)
    .eq('operation', operation)
    .single()

  if (!policy) return { allowed: true, requires_approval: false }
  return { allowed: true, requires_approval: policy.requires_approval }
}

// ── Audit Log ───────────────────────────────────────────────────
async function shimLogAudit(
  client: SupabaseClient,
  projectId: string,
  ctx: TrustContext,
  status: string,
  output?: unknown,
  duration_ms?: number
): Promise<string | null> {
  const { data } = await client
    .from('audit_log')
    .insert({
      project_id: projectId,
      session_id: ctx.session_id || null,
      agent_id: ctx.agent_id,
      tool_name: ctx.tool_name,
      operation_type: ctx.operation_type,
      input_hash: hashData(ctx.input),
      output_hash: hashData(output),
      status,
      duration_ms: duration_ms || null,
      requires_human_approval: status === 'pending_approval',
    } as never)
    .select('id')
    .single()

  return data?.id || null
}

// ── Public API ──────────────────────────────────────────────────

const DEV_OVERRIDE_TOKEN = 'allow-unconfigured-writes'

function devOverrideActive(): boolean {
  return process.env.PLATFORM_TRUST_DEV_OVERRIDE === DEV_OVERRIDE_TOKEN
}

/**
 * Run the full trust pipeline: rate limit → permission check → audit log.
 * Call BEFORE executing any operation.
 *
 * @param ctx - operation context
 * @param config - optional BYOK config. Pass `supabaseUrl` / `serviceKey` /
 *   `projectId` to point at YOUR trust-events Supabase project; otherwise
 *   falls back to the `PLATFORM_TRUST_*` env vars.
 *
 * Unconfigured behaviour (no config + no env vars):
 *   read           → allowed, warning logged
 *   write / delete → DENIED with denial_reason naming the missing fields,
 *                    UNLESS PLATFORM_TRUST_DEV_OVERRIDE='allow-unconfigured-writes'
 *                    is set, in which case allowed with a loud warning.
 */
export async function trustGate(
  ctx: TrustContext,
  config?: PlatformTrustConfig,
): Promise<TrustGateResult> {
  const { client, resolved } = getTrustClient(config)

  if (!client || !resolved) {
    const isMutation = ctx.operation_type === 'write' || ctx.operation_type === 'delete'

    if (isMutation && !devOverrideActive()) {
      console.error(
        `[platform-trust] DENIED ${ctx.operation_type} on scope="${ctx.scope}" tool="${ctx.tool_name}": ` +
        'platform-trust config unset. Pass { supabaseUrl, serviceKey, projectId } to trustGate(), ' +
        'or set PLATFORM_TRUST_SUPABASE_URL / PLATFORM_TRUST_SERVICE_KEY / PLATFORM_TRUST_PROJECT_ID env vars. ' +
        'To temporarily allow unconfigured writes in local dev, set ' +
        `PLATFORM_TRUST_DEV_OVERRIDE='${DEV_OVERRIDE_TOKEN}' (never in production).`
      )
      return {
        allowed: false,
        requires_approval: false,
        denial_reason:
          'Platform Trust not configured: write/delete denied. Pass { supabaseUrl, serviceKey, projectId } ' +
          'to trustGate() or set the PLATFORM_TRUST_* env vars.',
      }
    }

    if (isMutation) {
      console.warn(
        `[platform-trust] DEV-OVERRIDE active: allowing unconfigured ${ctx.operation_type} on ` +
        `scope="${ctx.scope}". This must NEVER fire in production.`
      )
    } else {
      console.warn('[platform-trust] Not configured, allowing read operation')
    }
    return { allowed: true, requires_approval: false }
  }

  const rateResult = await shimCheckRateLimit(client, resolved.projectId, ctx.agent_id)
  if (!rateResult.allowed) {
    await shimLogAudit(client, resolved.projectId, ctx, 'rate_limited')
    return {
      allowed: false,
      requires_approval: false,
      denial_reason: `Rate limit exceeded. Retry after ${rateResult.retry_after}s.`,
      retry_after: rateResult.retry_after,
    }
  }

  const permResult = await shimCheckPermission(client, resolved.projectId, ctx.agent_id, ctx.scope, ctx.operation_type)
  if (!permResult.allowed) {
    await shimLogAudit(client, resolved.projectId, ctx, 'permission_denied')
    return {
      allowed: false,
      requires_approval: false,
      denial_reason: `No permission for agent="${ctx.agent_id}" scope="${ctx.scope}" operation="${ctx.operation_type}".`,
    }
  }

  if (permResult.requires_approval) {
    const audit_id = await shimLogAudit(client, resolved.projectId, ctx, 'pending_approval')
    return { allowed: true, requires_approval: true, audit_id: audit_id || undefined }
  }

  return { allowed: true, requires_approval: false }
}

/**
 * Log a completed operation to the audit trail.
 * Call AFTER a successful operation.
 */
export async function trustLog(
  ctx: TrustContext,
  output: unknown,
  duration_ms: number,
  config?: PlatformTrustConfig,
): Promise<void> {
  const { client, resolved } = getTrustClient(config)
  if (!client || !resolved) return
  await shimLogAudit(client, resolved.projectId, ctx, 'completed', output, duration_ms)
}

/**
 * Record token usage for metering.
 * Call after any AI model call.
 */
export async function trustMeter(
  agent_id: string,
  model: string,
  input_tokens: number,
  output_tokens: number,
  session_id?: string,
  config?: PlatformTrustConfig,
): Promise<void> {
  const { client, resolved } = getTrustClient(config)
  if (!client || !resolved) return

  const pricing: Record<string, { input: number; output: number }> = {
    'claude-opus-4-6': { input: 0.000015, output: 0.000075 },
    'claude-sonnet-4-6': { input: 0.000003, output: 0.000015 },
    'claude-haiku-4-5': { input: 0.0000008, output: 0.000004 },
  }
  const p = pricing[model] || pricing['claude-sonnet-4-6']
  const cost_usd = input_tokens * p.input + output_tokens * p.output

  await client
    .from('metering_events')
    .insert({
      project_id: resolved.projectId,
      session_id: session_id || null,
      agent_id,
      model,
      input_tokens,
      output_tokens,
      cost_usd,
    } as never)
}
