// SCRUM-333 (Phase 1): assemble the "council-ready pack" — one zip of the
// project's current drawings + certifications + latest compliance report, so
// the user can lift it out and send it to council. This module holds the pure,
// testable assembly (bytes → zip + README); the API route does the DB/storage
// fetching and calls assembleCouncilPackZip.

import JSZip from "jszip";

/** One file to place in the pack, at `path` inside the zip. */
export interface PackPart {
  path: string;
  bytes: Uint8Array;
}

/** A filesystem-safe slug for the download filename. */
export function slugify(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "project"
  );
}

/**
 * The README/manifest that ships at the root of the pack, so a council officer
 * (or the user) can see at a glance what's inside and when it was compiled.
 * `generatedAt` is passed in (never read the clock here) so the output is
 * deterministic and testable.
 */
export function buildPackReadme(
  projectName: string,
  paths: string[],
  generatedAt: string,
): string {
  const lines = [
    `Council submission pack — ${projectName}`,
    `Compiled: ${generatedAt}`,
    "",
    "This pack contains the latest version of each document for this project.",
    "",
    "Contents:",
    ...paths.map((p) => `  - ${p}`),
    "",
    "Generated by MMC Build.",
  ];
  return lines.join("\n");
}

/**
 * Build the pack zip from already-fetched parts. Pure (no DB/storage/clock) so
 * it can be unit-tested. Adds a README manifest at the root.
 */
export async function assembleCouncilPackZip(
  projectName: string,
  parts: PackPart[],
  generatedAt: string,
): Promise<Uint8Array> {
  const zip = new JSZip();
  for (const part of parts) {
    zip.file(part.path, part.bytes);
  }
  zip.file(
    "README.txt",
    buildPackReadme(projectName, parts.map((p) => p.path), generatedAt),
  );
  return zip.generateAsync({ type: "uint8array" });
}
